### ISSUE TITLE
Roadmap of features

### ISSUE THREAD

**Issue by xkilian** [vbessler/grafana-pictureit#27]
*NOTE: A ~~fork~~ new plugin maintained by TLMiot has implemented almost ALL of these features. There is really no longer any reason to use vbessler/pictureit. See : [https://github.com/pierosavi/pierosavi-imageit-panel](https://github.com/pierosavi/pierosavi-imageit-panel/) It is not yet publised on the Grafana panel list.

Some of the features already have patches available, some are open issues, some are ideas that I see are the minimum for having a usable graphical canvas type plugin panel. 

- [ ] Plugin compatibility with Grafana 5, 6 (TLMiot new plugin)
- [ ] Plugin canvas compatible with larger images (TLMiot new plugin)
- [ ] Links on sensors (TLMiot new plugin)
- [ ] Compatible with variables/templates (TLMiot new plugin)
- [ ] Sensor colour changing on threshold change (Use similar threshold logic as Vonage Status Panel or Single Stats) Have Text or box background colour change (selectable) (TLMiot new plugin)
- [ ] Text/Emoji mapping of values (TLMiot new plugin)
- [ ] Sensor text output
- [ ] Draggable sensors (TLMiot new plugin)
- [ ] Borderless sensors (just the value) (TLMiot new plugin)
- [ ] Line sensors (value show out aligned in the middle of the line) with optional arrows, like in Nagvis
- [ ] Sensor as a user provided vector graphic with sensor value offset left,right,top or bottom of vector image, like in Nagvis. Instead of just a box with a value in it.
- [ ] Show a metrics list on mouseover (If permitting multiple values like Vonage Status Panel)

**Comment by mlavelle42** [comment]
I second this feature list. Including:
- Scalable images to fit different size panels
- Links on sensors - valuable to zoom to details
- Color variation - as a function of value/limits
- Draggable sensors - important time-saver to simplify positioning

**Comment by TLMiot** [comment]
This repo seems dead, so in my [fork](https://github.com/TLMiot/grafana-pictureit) I implemented some of these features, including

-  Plugin compatibility with Grafana 5
-  Plugin canvas compatible with larger images
-  Links on sensors
-  Draggable sensors

I could actively mantain it if there are people interested

**Comment by mlavelle42** [comment]
I'll try it and let you know.

**Comment by gregjewi** [comment]
@TLMiot could you address this feature request in your fork? https://github.com/vbessler/grafana-pictureit/issues/15 

Thanks!

**Comment by TLMiot** [comment]
> @TLMiot could you address this feature request in your fork? #15
> 
> Thanks!

Sorry I just saw your comment, please open an issue directly on my fork next time so I see it faster. I will continue the conversation in the issue 

Edit: I just pushed the update to my fork

**Comment by xkilian** [comment]
@TLMiot Great fork. I would actually suggest you contact the Grafana team and suggest they deprecate the old plugin, add a note that the original auther is MIA. The easiest would be to rename the project and drop the "fork" status and submit it to the Grafana team. Of course someone who is more familiar with how github works can suggest something more intelligent. ;-)
Just saying. Anyway, love the work you have done. This has always been a major lacking feature of Grafana, I even had someone hack Nagvis to get metrics on a nice canvas... I will port my feature request list to your plugin and will follow your work.  :-)

**Comment by xkilian** [comment]
As TLMiot mentioned, this plugin is dead, was forked and now has been remade into a new one that is actually maintained: See [https://github.com/pierosavi/pierosavi-imageit-panel](https://github.com/pierosavi/pierosavi-imageit-panel/)

See the roadmap issue which is almost almost complete!

**Comment by pierosavi** [comment]
Just to be clear I moved the fork to my personal account, I dropped the status of fork and it is under review to be published in plugin list [over here](https://github.com/grafana/grafana-plugin-repository/pull/403). If it gains some popularity I'll ask the grafana team to deprecate the old one
